use hr;

select 5 = null;
select 'ab' = null;
select true = null;
select null = null;
select '' and null;
select concat('hi',null);

-- Count
select count(*) from employees; -- count all row
select count(minimum_reorder_quantity) from northwind.products;  -- count only valid values

select * from orders;
select count(customer_id) from orders;
select count(employee_id) from orders where customer_id is not null;

-- no of customer from newyork city
select count(distinct customer_id) from orders where ship_city = 'New York';

select sum(salary) from hr.employees where salary is not null;

-- find the total revenue generated by company
select sum(quantity*unit_price-discount) Total_Revenue from order_details;

-- Average
select avg(salary) from hr.employees;

select avg(unit_price) Average from northwind.order_details;

select avg(quantity) Average from northwind.order_details;

-- min and max
select min(unit_price) minimun_unit_price, max(unit_price) Max_unit_price from northwind.order_details;

-- group by 
select first_name, count(department_id) no_of_emp, avg(exp)
from employees 
group by department_id;
/*
Error Code: 1055. 
Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated 
column 'hr.employees.FIRST_NAME' 
which is not functionally dependent on columns in GROUP BY clause;
this is incompatible with sql_mode=only_full_group_by
*/
select department_id, count(department_id) no_of_emp, avg(exp)
from employees 
group by department_id;

select salary, count(*)
from employees
group by salary;

select category, count(*) no_of_product_cat
from northwind.products
where category = 'Beverages'
group by category;

-- find total no of order of each customers
select customer_id, count(order_date) from northwind.orders group by customer_id;

-- find total revenue for each product
select product_name, sum(standard_cost*list_price) total_revenue from northwind.products group by product_name order by total_revenue desc;

-- find no of employee has hire_date before 1988 for each dept
select 
	department_id, 
    count(hire_date) 
from employees 
where year(hire_date) < '1988' 
group by DEPARTMENT_ID 
order by DEPARTMENT_ID;
 
-- max salary in each dept
select 
	department_id, 
    max(salary) max_salary 
from employees 
group by DEPARTMENT_ID;
select * from employees;
select 
	department_id, 
    min(salary) min_salary 
from employees 
group by DEPARTMENT_ID;

-- find min and max salary for each job_id where department id = 80
select 
	department_id, 
    max(salary) max_salary,
    min(salary) min_salary,
    job_id
from employees 
where department_id = 80
group by job_id;

-- find distinct job role in each dept
select 
	distinct (job_id),
    department_id
from employees;

select 
	count(distinct (job_id)) counts,
    department_id
from employees
group by department_id;

-- Order of execution
# from -> where -> group by -> aggrigate -> having -> select

select manager_id, count(*) no_of
from hr.employees
group by manager_id
having no_of > 5
order by no_of desc;
select * from employees;
-- no of customers who have placed more than 5 people
select 
	customer_id, 
    count(*) as no_of
from northwind.orders
group by customer_id
having no_of > 5
order by no_of desc;

-- find shipper have shipped more than 100 orders in year 
select shipper_id, count(*) count from northwind.orders  where year(shipped_date) = '2006' group by shipper_id having count > 10;

-- find dept, total salary exceeds 50000
select department_id, sum(salary) total_revenue from employees group by department_id having total_revenue > 50000;

-- find dept avg salary is between 5000 to 10000
select department_id, avg(salary) avg_salary from employees group by department_id having avg_salary between 5000 and 10000;

-- find dept where min and max salary is greater than 5000
select 
	department_id, 
    max(salary) max_salary,
    min(salary) min_salary
from employees 
where department_id = 80
group by department_id
having max_salary-min_salary > 5000;

-- 
select
	case
		when salary < 8000 then 'low salary'
        when salary < 10000 then 'mid salary'
        when salary < 50000 then 'high salary'
        else 'high'
	end salary_band,
    count(*) no_of,
    min(salary) min_salary,
    max(salary) max_salary
from employees
group by
    case
		when salary < 8000 then 'low salary'
        when salary < 10000 then 'mid salary'
        when salary < 50000 then 'high salary'
        else 'high'
	end
order by no_of desc;
# group by -> case -> sort -> aggrigate -> select

select upper(first_name) from employees;
select lower(last_name) from employees;

select first_name, length(first_name) from employees;
select first_name, char_length(first_name) from employees;
select first_name, bit_length(first_name) from employees;

select first_name, concat(first_name,' ', last_name) from employees;
select first_name, concat_ws('-',first_name,last_name) from employees;

select first_name, substring(first_name,2,3) from employees;
select first_name, substring(first_name,2) from employees;
select first_name, left(first_name,2) from employees;
select first_name, right(first_name,3) from employees;

select first_name,replace(phone_number,'.','-') from employees;

select phone_number, instr(phone_number,'.') from employees;

select first_name,reverse(first_name) from employees;

select first_name,repeat('*',floor(salary/5000)) as star from employees;

select salary, floor(salary/5000) from employees;